name: Publish to NPM

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.0'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Run pre-publish build
        run: npm run pre-publish

      - name: Update version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version patch

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc
          npm publish

      - name: Push changes
        if: success()
        run: |
          git push origin HEAD:main
